# Generated by Django 5.2.7 on 2025-11-01 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_studentprofile_address_studentprofile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='avatar_url',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
