# Generated by Django 5.2.7 on 2025-11-02 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_studentprofile_avatar_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='govt_Id',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
