# Generated by Django 5.2.7 on 2025-11-07 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0002_assessmenttype_classroom_subject_enrollment_and_more'),
        ('school', '0002_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='school.classroom'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='school.subject'),
        ),
        migrations.DeleteModel(
            name='Classroom',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
